# Generated by Django 4.2.1 on 2023-12-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='men',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='men.category'),
        ),
        migrations.AddField(
            model_name='men',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='men.tagpost'),
        ),
        migrations.AddField(
            model_name='men',
            name='wife',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men', to='men.wife'),
        ),
        migrations.AddIndex(
            model_name='men',
            index=models.Index(fields=['-time_create'], name='men_men_time_cr_642e6a_idx'),
        ),
    ]
